#!/bin/sh
# fixing rustup
# Correct and extend PATH
export PATH="$HOME/.local/bin:$HOME/local/share/go/bin:$HOME/.miniconda/bin:$PATH"

HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=100000
SAVEHIST=100000
# Correct way to extend PATH
export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"

export MANPAGER='nvim +Man!'
export MANWIDTH=999

# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
        . "$HOME/.miniconda/etc/profile.d/conda.sh"
    else
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
